### ISSUE TITLE
components missing

### ISSUE THREAD

**Issue by Zeitvertreib** [wesssel/vue-pug-stylus#1]
Recently stumbled upon pug. ..ofc I wanted to integrate. and I read your post, and I like it, also I like this github blueprint for the integration.
But I'm missing the easy src/components folder and so forth.
..would totally star this if it had it.

regards

**Comment by wesssel** [comment]
@Zeitvertreib  personally I think having a `src` folder is not necessary in this kind of project.

**Comment by Zeitvertreib** [comment]
How is this project meant to be used without a `src` folder if creating it is not the next step?
